### ISSUE TITLE
Не хватает компонентов: грейдирование

### ISSUE THREAD

**Issue by effus** [effus/team-builder#6]
![](https://i.ibb.co/vXbjRFr/2020-11-13-09-02-28.png)

**Comment by evgenykon** [comment]
https://github.com/effus/team-builder/issues/29 наполнение страницы

**Comment by evgenykon** [comment]
https://github.com/effus/team-builder/issues/30 Performance review

**Comment by evgenykon** [comment]
https://github.com/effus/team-builder/issues/31 Goals

**Comment by evgenykon** [comment]
https://github.com/effus/team-builder/issues/32 форма добавления грейдирования

**Comment by evgenykon** [comment]
https://github.com/effus/team-builder/issues/33 форма проведения грейдирования
